<Project>
   <PropertyGroup>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
      <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
      
      <AnalysisLevel>latest</AnalysisLevel>

      <BaseArtifactsPath>$(MSBuildThisFileDirectory)bin</BaseArtifactsPath>
      <OutputPath>$(BaseArtifactsPath)\$(Platform)\$(Configuration)\$(MSBuildProjectName)\</OutputPath>
      <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>

      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
   </ItemGroup>
</Project>
