<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Build5Nines.SharpVector" Version="2.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.26.0" />
    <PackageReference Include="Tokenizers.DotNet" Version="1.4.1" />
    <PackageReference Include="Tokenizers.DotNet.runtime.win-x64" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Synapse.Engine.Abstraction\Synapse.Engine.Abstraction.csproj" />
  </ItemGroup>

</Project>
